<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5b9a5c8e02bbb',
	'title' => 'Flexible Layout',
	'fields' => array(
		array(
			'key' => 'field_5b9a607a53f00',
			'label' => 'individual Columns',
			'name' => 'ind-columns',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5b9a6452a3a5f' => array(
					'key' => '5b9a6452a3a5f',
					'name' => 'mehrspaltiges_layout',
					'label' => 'mehrspaltiges Layout',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5bb624e3aaa84',
							'label' => 'Seitenverhältnis',
							'name' => 'proportion',
							'type' => 'radio',
							'instructions' => 'in welchem Seitenverhältnis soll das Layout angezeigt werden?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'default' => 'Bitte wählen',
								'50-50' => 'zwei Spalten gleichmäßig',
								'3x40' => 'drei Blöcke gleichmäßig',
								'4x30' => '4 Blöcke gleichmäßig',
								100 => 'volle Breite',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5b9a674dc2dba',
							'label' => 'Spalten',
							'name' => 'columns',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5bb624e3aaa84',
										'operator' => '!=',
										'value' => 'default',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'row',
							'button_label' => 'Eintrag hinzufügen',
							'sub_fields' => array(
								array(
									'key' => 'field_5b9a6771c2dbb',
									'label' => 'Textblock',
									'name' => 'textblock',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array(
									'key' => 'field_5c2de152ac670',
									'label' => 'Textblock hervorheben',
									'name' => 'highlight_block',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'ja',
									'default_value' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5c2de179ac671',
									'label' => 'Textblock Styles',
									'name' => 'textblock-styles',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5c2de152ac670',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'border' => 'nur ein Rand',
										'bg-primary' => 'Primärfarbe',
										'bg-secondary' => 'Sekundärfarbe',
										'custom-color' => 'eigene Farbwahl',
									),
									'allow_null' => 1,
									'other_choice' => 0,
									'default_value' => '',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5c2dea009fd7b',
									'label' => 'Hintergrundfarbe',
									'name' => 'bg-color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5c2de179ac671',
												'operator' => '==',
												'value' => 'custom-color',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#ffffff',
								),
								array(
									'key' => 'field_5c2dea349fd7c',
									'label' => 'Textfarbe',
									'name' => 'textfarbe',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5c2de179ac671',
												'operator' => '==',
												'value' => 'custom-color',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#000000',
								),
							),
						),
					),
					'min' => '0',
					'max' => '4',
				),
			),
			'button_label' => 'Reihe hinzufügen',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page_columns.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c28b8f7b0504',
	'title' => 'Sidebar Layout',
	'fields' => array(
		array(
			'key' => 'field_5c28b98c07326',
			'label' => 'Position',
			'name' => 'position_sidebar',
			'type' => 'radio',
			'instructions' => 'Wo soll die Sidebar positioniert werden?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'links',
				'right' => 'rechts',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'right',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5c28bfda1e45f',
			'label' => 'Welche Sidebar?',
			'name' => 'welche_sidebar',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'standard (inkl. Widgets)',
				'custom' => 'individuell (= ohne Widgets, inkl. ind. Textblöcke)',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5c28b83969538',
			'label' => 'Custom Sidebar',
			'name' => 'custom_sidebar',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c28bfda1e45f',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5c28cfbf14e81',
					'label' => 'Textblock',
					'name' => 'textblock',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5c28d11b3d87c',
					'label' => 'Textblock hervorheben',
					'name' => 'highlight_block',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'ja',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5c28d203b5a5f',
					'label' => 'Textblock-Styles',
					'name' => 'textblock-styles',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c28d11b3d87c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'border' => 'nur ein Rand',
						'bg-primary' => 'Primärfarbe',
						'bg-secondary' => 'Sekundärfarbe',
						'custom-color' => 'eigene Farbwahl',
					),
					'allow_null' => 1,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_5c28d293f66a6',
					'label' => 'Hintergrundfarbe',
					'name' => 'bg-color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c28d203b5a5f',
								'operator' => '==',
								'value' => 'custom-color',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5c28dd76e5604',
					'label' => 'Textfarbe',
					'name' => 'textfarbe',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5c28d203b5a5f',
								'operator' => '==',
								'value' => 'custom-color',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page_inkl_sidebar.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c53092a24acf',
	'title' => 'Carousel-Slider',
	'fields' => array(
		array(
			'key' => 'field_5c3efe4b07874',
			'label' => 'Slider-Bilder',
			'name' => 'slider-images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => 1165,
			'min_height' => 415,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, png',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
 ?>
